### ISSUE TITLE
Constraints the image type

### ISSUE THREAD

**Issue by ariG23498** [soumik12345/restorers#18]
https://github.com/soumik12345/mirnetv2/blob/0dd215b926f772f34c7ed208f0ac7fc24e7e4af4/mirnetv2/dataloader/base/base_dataloader.py#L33

I feel this link constraints the image type to only `pngs`. I would like to hear what you all think about this.

**Comment by soumik12345** [comment]
@ariG23498 I think we can resolve this constraint by using
```python
image = tf.io. decode_image(image, channels=3) 
```

Reference: https://www.tensorflow.org/api_docs/python/tf/io/decode_image

**Comment by SauravMaheshkar** [comment]
> @ariG23498 I think we can resolve this constraint by using
> 
> ```python
> image = tf.io.decode_image(image, channels=3) 
> ```
> 
> Reference: https://www.tensorflow.org/api_docs/python/tf/io/decode_image

Yup this should work

**Comment by ariG23498** [comment]
I will link this to the PR that I am developing!

**Comment by SauravMaheshkar** [comment]
Closed by #20
