### ISSUE TITLE
Bug: build backend is missing the 'build_editable' hook

### ISSUE THREAD

**Issue by soumik12345** [soumik12345/restorers#43]
While trying to install restorers on colab using `pip install -q --upgrade git+https://github.com/soumik12345/restorers.git`, it threw the following error:

```
ERROR: Project file:///content/restorers has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

**Comment by soumik12345** [comment]
cc: @SauravMaheshkar

**Comment by SauravMaheshkar** [comment]
Could you update your version of `pip` and `setuptools` and try again.

**Comment by soumik12345** [comment]
> Could you update your version of `pip` and `setuptools` and try again.

It worked @SauravMaheshkar. Is there a fix to this issue so that users don't have to update `pip` and `setuptools` for installing `restorers`?

**Comment by SauravMaheshkar** [comment]
> > Could you update your version of `pip` and `setuptools` and try again.
> 
> It worked @SauravMaheshkar. Is there a fix to this issue so that users don't have to update `pip` and `setuptools` for installing `restorers`?

Not that I'm aware of, `pyproject.toml` is the newer standard for python packaging and therefore support for stuff like editable installs, is fairly new. We could try a new backend which supports `PEP660` by default such as `flit`.

**Comment by SauravMaheshkar** [comment]
Any further comments or feedback on this ??

**Comment by soumik12345** [comment]
> Any further comments or feedback on this ??

Don't think so, have been facing this issue only on Kaggle and Colab, I think probably the issue is with their outdated container images.
